### ISSUE TITLE
Users without permission can edit links

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/linklist#42]
Users who are not member a of space do not see the menu entry, but the can access the module options via corresponding link (e.g. (https://server/s/space-I-am-following/linklist/linklist). They are also able to add/edit entries without any permission. The module seems to have some general issues, also see: https://github.com/humhub-contrib/linklist/issues/30

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look here? If we are already doing something on this module, can you add some basic tests and generally review the module from a code point of view and optimize it if necessary?

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub-contrib/linklist/pull/43
