### ISSUE TITLE
Remove CActiveForm

### ISSUE THREAD

**Issue by funkycram** [humhub-contrib/linklist#49]
This module is not working anymore with Humhub 1.11 because of CActiveForm.

**Comment by luke-** [comment]
@yurabakhtin Can you take a look into this?

**Comment by yurabakhtin** [comment]
@luke- It was done here https://github.com/humhub-contrib/linklist/pull/47, but the changes were not released yet.

**Comment by luke-** [comment]
@yurabakhtin Ah thanks! I'll do it now...
